sudo: false
language: java
node_js: node

addons:
  apt:
    packages:
      - oracle-java8-installer

branches:
  only:
  - master

os: linux

cache:
  directories:
  - $HOME/.m2
  - src/main/ui/node_modules

jdk: oraclejdk8

script:
- (cd src/main/ui ; npm install ; ./node_modules/.bin/gulp)
- mvn package
